name: masamune_list
description: >-
  Plugin for implementing the functions of list.
version: 0.4.0+3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_list

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bordered_text: ^1.0.0
  # Masamune
  masamune_flutter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
